replicas: 1

service:
  type: LoadBalancer

# adminUser: admin
# adminPassword: admin123

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local:80
      access: proxy
      isDefault: true
      editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ""
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards

dashboards:
  default:
    kubernetes-cluster:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    fastapi-metrics:
      gnetId: 11074
      revision: 1
      datasource: Prometheus
