apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          {{- if .value }}
          value: "{{ .value }}"
          {{- end }}
          {{- if .valueFrom }}
          valueFrom:
            fieldRef:
              fieldPath: {{ .valueFrom.fieldRef.fieldPath }}
          {{- end }}
        {{- end }}
