apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-apps
  namespace: argocd
spec:
  source:
    repoURL: https://gitlab.com/your-org/fastapi-k8s-platform.git
    path: argocd/applications
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
