apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://192.168.0.190/root/project_nebula.git
    path: monitoring/grafana
    targetRevision: main
    helm:
      values: |
        replicas: 1
        service:
          type: LoadBalancer
        persistence:
          enabled: true
          size: 1Gi
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
              access: proxy
              isDefault: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
