apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://192.168.0.190/root/project_nebula.git
    path: monitoring/prometheus
    targetRevision: main
    helm:
      values: |
        server:
          replicaCount: 1
          service:
            type: LoadBalancer
          retention: "30d"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          persistentVolume:
            enabled: false
        alertmanager:
          enabled: true
        pushgateway:
          enabled: false
        nodeExporter:
          enabled: false
        kubeStateMetrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10
